# Generated by Django 4.1.5 on 2023-02-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='emails',
            new_name='email',
        ),
    ]
